import { readFile } from "node:fs/promises";
import path from "node:path";

import type { ArtifactVersion } from "../artifact-store.js";
import type { LearningUnitPlan } from "../corpus-types.js";
import { buildLessonCriticReport } from "../quality/lesson-critic.js";
import { normalizeSources } from "../source/source-normalizer.js";
import type { RunConfig } from "../types.js";
import type { RoleId, WorkflowArtifactId } from "../workflow/role-sequence.js";

export type RuntimeAdapter = {
  executeRole(context: RuntimeAdapterContext): Promise<RuntimeAdapterResult>;
};

export type RuntimeAdapterContext = {
  config: RunConfig;
  runPath: string;
  roleId: RoleId;
  artifactId: WorkflowArtifactId;
};

export type RuntimeAdapterResult =
  | {
      kind: "artifact";
      payload: unknown;
    }
  | {
      kind: "manual_action_required";
      roleId: RoleId;
      artifactId: WorkflowArtifactId;
      promptPath: string;
      expectedVersion?: ArtifactVersion;
      message: string;
    };

export class MockRuntimeAdapter implements RuntimeAdapter {
  async executeRole({ config, runPath, roleId, artifactId }: RuntimeAdapterContext): Promise<RuntimeAdapterResult> {
    if (roleId === "corpus-ingest" && artifactId === "source-map") {
      const normalizedSources = await normalizeSources(config.sources);
      return artifactResult({
        artifactId,
        roleId,
        corpusId: config.runId,
        language: config.outputLanguage,
        sources: config.sources,
        structure: normalizedSources.structure,
        anchors: normalizedSources.anchors,
        extractionWarnings: normalizedSources.extractionWarnings,
        extractionNotes:
          normalizedSources.extractionWarnings.length > 0
            ? normalizedSources.extractionWarnings.map((warning) => warning.message)
            : ["Source map generated by the local normalizer."]
      });
    }

    if (roleId === "concept-mapper" && artifactId === "concept-map") {
      const sourceAnchorIds = await sourceAnchorIdsForConfig(config);
      const conceptSet = buildMockConceptSet(config, sourceAnchorIds);
      return artifactResult({
        artifactId,
        roleId,
        language: config.outputLanguage,
        concepts: conceptSet.concepts,
        dependencies: conceptSet.dependencies,
        misconceptions: conceptSet.misconceptions,
        examples: conceptSet.examples
      });
    }

    if (roleId === "curriculum-planner" && artifactId === "curriculum-plan") {
      const sourceAnchorIds = await sourceAnchorIdsForConfig(config);
      const conceptSet = buildMockConceptSet(config, sourceAnchorIds);
      const units = buildMockCourseUnits(config, sourceAnchorIds, conceptSet.conceptIds);
      const sourceCoverage = buildSourceCoverage(config, units, sourceAnchorIds);
      const conceptCoverage = buildConceptCoverage(conceptSet.conceptIds, units);
      const chapterMapping = buildChapterMapping(config, units);
      return artifactResult({
        artifactId,
        roleId,
        id: `${config.runId}-curriculum-plan`,
        corpusId: config.runId,
        mode: config.curriculumPlanningMode,
        userProfile: config.userLearningProfile,
        coveragePolicy: config.coveragePolicy,
        coursePack: {
          id: `${config.runId}-course-pack`,
          title: `${config.topic}：课程包`,
          sourceKind: config.sourceKind ?? "unknown",
          strategy: config.coursePack?.strategy ?? "overview_plus_topic",
          audience: config.audience,
          language: config.outputLanguage,
          overviewUnitId: units.find((unit) => unit.kind === "overview")?.id,
          units,
          sourceCoverage,
          conceptCoverage,
          chapterMapping
        },
        units,
        sourceCoverage,
        conceptCoverage,
        rationale: [
          "默认采用 overview_plus_topic：先给总览课，再按核心 topic 拆分学习单元。",
          "课程包保留 source/chapter 映射，后续每个 unit 可独立生成 Web Deck。"
        ]
      });
    }

    if (roleId === "source-ingest") {
      const selectedUnit = config.selectedUnit;
      const profile = buildMockLessonProfile(config);
      return artifactResult({
        artifactId,
        roleId,
        language: "zh-CN",
        topic: selectedUnit?.title ?? config.topic,
        selectedUnit,
        concepts: profile.concepts,
        dependencies: profile.dependencies,
        examples: profile.examples,
        misconceptions: profile.misconceptionStatements,
        candidateInteractions: profile.candidateInteractions
      });
    }

    if (roleId === "learning-architecture") {
      const selectedUnit = config.selectedUnit;
      const profile = buildMockLessonProfile(config);
      return artifactResult({
        artifactId,
        roleId,
        language: "zh-CN",
        audience: config.audience,
        selectedUnit,
        pageCount: {
          ...config.pageCount,
          planned: config.pageCount.target
        },
        prerequisites: profile.prerequisites,
        learningObjectives: profile.learningObjectives,
        pageSequence: buildPageSequence(config.pageCount.target, selectedUnit?.title, profile)
      });
    }

    if (roleId === "lesson-assembly" && artifactId === "lesson") {
      const selectedUnit = config.selectedUnit;
      const profile = buildMockLessonProfile(config);
      return artifactResult({
        id: selectedUnit ? config.runId : profile.defaultLessonId,
        title: selectedUnit?.title ?? profile.defaultTitle,
        audience: config.audience,
        config: {
          targetPageCount: config.pageCount.target,
          minPageCount: config.pageCount.min,
          maxPageCount: config.pageCount.max
        },
        sourceContext: selectedUnit
          ? {
              parentRunId: selectedUnit.parentRunId,
              parentCoursePackId: selectedUnit.parentCoursePackId,
              unitId: selectedUnit.id,
              sourceAnchorIds: selectedUnit.sourceAnchorIds,
              chapterRefs: selectedUnit.chapterRefs,
              conceptIds: selectedUnit.conceptIds
            }
          : undefined,
        language: "zh-CN",
        prerequisites: profile.prerequisites,
        learningObjectives: profile.learningObjectives,
        pages: buildLessonPages(config.pageCount.target, profile),
        misconceptions: profile.misconceptions,
        transferTasks: profile.transferTasks,
        summary: profile.summary
      });
    }

    if (roleId === "lesson-critic" && artifactId === "critic-report") {
      const rawLesson = await readFile(path.join(runPath, "artifacts", "lesson.approved.json"), "utf8");
      const lesson = JSON.parse(rawLesson) as unknown;
      return artifactResult({
        artifactId,
        roleId,
        ...buildLessonCriticReport(lesson, config)
      });
    }

    return artifactResult({
      artifactId,
      roleId,
      language: "zh-CN",
      topic: config.topic,
      status: "mocked",
      notes: `${roleId} 已生成 ${artifactId} 的占位草稿。`
    });
  }
}

async function sourceAnchorIdsForConfig(config: RunConfig): Promise<string[]> {
  const normalizedSources = await normalizeSources(config.sources);
  return normalizedSources.anchors.map((anchor) => anchor.anchorId);
}

function buildMockCourseUnits(config: RunConfig, sourceAnchorIds: string[], conceptIds: string[]): LearningUnitPlan[] {
  const unitPageCount = config.coursePack?.unitPageCount ?? config.userLearningProfile.preferredPageCountPerUnit ?? config.pageCount.target;
  const outputProducts: LearningUnitPlan["outputProducts"] = config.coursePack?.outputProducts ?? ["web_lesson", "assessment"];
  const requestedTopicLabels = config.coursePack?.selectedTopics;
  const defaultTopicLabels = ["核心机制", "常见误区", "迁移应用"];
  const topicLabels = requestedTopicLabels && requestedTopicLabels.length > 0 ? requestedTopicLabels : defaultTopicLabels;
  const preferredUnitCount = config.coursePack?.preferredUnitCount ?? (config.coursePack?.includeOverview === false ? 3 : 4);
  const units: LearningUnitPlan[] = [];

  if (config.coursePack?.includeOverview !== false) {
    units.push({
      id: "unit-overview",
      title: `${config.topic}：总览课`,
      kind: "overview",
      purpose: "先建立资料全局地图、核心问题和后续 topic 拆分方式。",
      targetPageCount: unitPageCount,
      sourceAnchorIds,
      sourceNodeIds: sourceNodeIdsForAnchors(config, sourceAnchorIds),
      chapterRefs: config.coursePack?.selectedChapters,
      conceptIds,
      outputProducts
    });
  }

  const remainingSlots = Math.max(1, preferredUnitCount - units.length);
  const selectedTopicLabels = topicLabels.slice(0, remainingSlots);
  for (const [index, label] of selectedTopicLabels.entries()) {
    const topicSourceAnchorIds = sourceAnchorSliceForTopic(sourceAnchorIds, index, selectedTopicLabels.length);
    units.push({
      id: `unit-topic-${String(index + 1).padStart(2, "0")}`,
      title: `${config.topic}：${label}`,
      kind: "topic",
      purpose: "围绕一个核心 topic 建立可操作的心智模型、误区检查和迁移任务。",
      targetPageCount: unitPageCount,
      sourceAnchorIds: topicSourceAnchorIds,
      sourceNodeIds: sourceNodeIdsForAnchors(config, topicSourceAnchorIds),
      chapterRefs: config.coursePack?.selectedChapters,
      conceptIds: conceptIdsForTopic(conceptIds, index, selectedTopicLabels.length),
      outputProducts
    });
  }

  return units;
}

function buildSourceCoverage(
  config: RunConfig,
  units: LearningUnitPlan[],
  sourceAnchorIds: string[]
): Array<{ sourceNodeId: string; status: "covered" | "partial" | "deferred" | "omitted"; unitIds: string[]; notes?: string }> {
  return config.sources.map((source) => {
    const sourceSpecificAnchors = sourceAnchorIds.filter((anchorId) => anchorBelongsToSource(anchorId, source.id));
    const unitIds = units
      .filter((unit) => unit.sourceAnchorIds.some((anchorId) => anchorBelongsToSource(anchorId, source.id)))
      .map((unit) => unit.id);
    const coveredAnchors = new Set(
      units.flatMap((unit) => unit.sourceAnchorIds.filter((anchorId) => anchorBelongsToSource(anchorId, source.id)))
    );
    const fullyCovered = sourceSpecificAnchors.every((anchorId) => coveredAnchors.has(anchorId));
    const status = unitIds.length === 0 ? "omitted" : fullyCovered ? "covered" : "partial";

    return {
      sourceNodeId: `${source.id}:root`,
      status,
      unitIds,
      ...(status === "partial" ? { notes: "部分来源锚点进入 topic 单元；总览课保留全局映射。" } : {}),
      ...(status === "omitted" ? { notes: "当前课程计划未覆盖该来源。" } : {})
    };
  });
}

function buildConceptCoverage(
  conceptIds: string[],
  units: LearningUnitPlan[]
): Array<{ conceptId: string; status: "covered" | "partial" | "deferred" | "omitted"; unitIds: string[]; notes?: string }> {
  return conceptIds.map((conceptId) => {
    const unitIds = units.filter((unit) => unit.conceptIds.includes(conceptId)).map((unit) => unit.id);
    return {
      conceptId,
      status: unitIds.length > 0 ? "covered" : "omitted",
      unitIds,
      ...(unitIds.length === 0 ? { notes: "当前课程计划未覆盖该概念。" } : {})
    };
  });
}

function buildChapterMapping(
  config: RunConfig,
  units: LearningUnitPlan[]
): Array<{ chapterId: string; title: string; unitIds: string[]; anchorIds: string[] }> {
  return config.sources.map((source) => {
    const sourceUnitIds = units
      .filter((unit) => unit.sourceAnchorIds.some((anchorId) => anchorBelongsToSource(anchorId, source.id)))
      .map((unit) => unit.id);
    const anchorIds = uniqueStrings(
      units.flatMap((unit) => unit.sourceAnchorIds.filter((anchorId) => anchorBelongsToSource(anchorId, source.id)))
    );

    return {
      chapterId: `${source.id}:root`,
      title: source.title,
      unitIds: sourceUnitIds,
      anchorIds
    };
  });
}

function sourceAnchorSliceForTopic(sourceAnchorIds: string[], topicIndex: number, topicCount: number): string[] {
  if (sourceAnchorIds.length === 0) {
    return [];
  }
  if (topicCount <= 1) {
    return [...sourceAnchorIds];
  }
  if (sourceAnchorIds.length <= topicCount) {
    return [sourceAnchorIds[topicIndex % sourceAnchorIds.length] as string];
  }

  const chunkSize = Math.ceil(sourceAnchorIds.length / topicCount);
  const start = topicIndex * chunkSize;
  const chunk = sourceAnchorIds.slice(start, Math.min(sourceAnchorIds.length, start + chunkSize));
  return chunk.length > 0 ? chunk : [sourceAnchorIds[topicIndex % sourceAnchorIds.length] as string];
}

function conceptIdsForTopic(conceptIds: string[], topicIndex: number, topicCount: number): string[] {
  if (conceptIds.length === 0) {
    return [];
  }
  if (topicCount <= 1) {
    return [...conceptIds];
  }
  if (conceptIds.length <= topicCount) {
    return [conceptIds[topicIndex % conceptIds.length] as string];
  }

  const chunkSize = Math.ceil(conceptIds.length / topicCount);
  const start = topicIndex * chunkSize;
  const chunk = conceptIds.slice(start, Math.min(conceptIds.length, start + chunkSize));
  return chunk.length > 0 ? chunk : [conceptIds[topicIndex % conceptIds.length] as string];
}

function sourceNodeIdsForAnchors(config: RunConfig, sourceAnchorIds: string[]): string[] {
  const sourceIds = uniqueStrings(
    config.sources
      .filter((source) => sourceAnchorIds.some((anchorId) => anchorBelongsToSource(anchorId, source.id)))
      .map((source) => `${source.id}:root`)
  );
  return sourceIds.length > 0 ? sourceIds : config.sources.map((source) => `${source.id}:root`);
}

function anchorBelongsToSource(anchorId: string, sourceId: string): boolean {
  return anchorId.startsWith(`${sourceId}:`);
}

function uniqueStrings(values: string[]): string[] {
  return Array.from(new Set(values));
}

function artifactResult(payload: unknown): RuntimeAdapterResult {
  return {
    kind: "artifact",
    payload
  };
}

function buildPageSequence(targetPageCount: number, selectedUnitTitle: string | undefined, profile: MockLessonProfile): string[] {
  const baseSequence = profile.pageSequence;

  return Array.from({ length: targetPageCount }, (_, index) => {
    const title = baseSequence[index % baseSequence.length];
    return selectedUnitTitle ? `${selectedUnitTitle} / ${title}` : title;
  });
}

type MockConceptSet = {
  conceptIds: string[];
  concepts: Array<Record<string, unknown>>;
  dependencies: Array<Record<string, unknown>>;
  misconceptions: Array<Record<string, unknown>>;
  examples: Array<Record<string, unknown>>;
};

type MockLessonProfile = {
  defaultLessonId: string;
  defaultTitle: string;
  concepts: string[];
  dependencies: string[];
  examples: string[];
  misconceptionStatements: string[];
  candidateInteractions: string[];
  prerequisites: string[];
  learningObjectives: string[];
  pageSequence: string[];
  misconceptions: Array<Record<string, string>>;
  transferTasks: Array<Record<string, string>>;
  summary: string[];
  pageKind: "database-index" | "agentic";
};

type MockBasePage = {
  type: string;
  title: string;
  learningGoal: string;
  narrative: string;
  visualSpec?: Record<string, unknown>;
  interactionSpec?: Record<string, unknown>;
  assessmentSpec?: Record<string, unknown>;
  feedbackSpec?: Record<string, unknown>;
};

function buildMockConceptSet(config: RunConfig, sourceAnchorIds: string[]): MockConceptSet {
  if (isAgenticTopic(config.topic)) {
    const conceptIds = ["agent-loop", "tool-use", "multi-agent-review"];
    return {
      conceptIds,
      concepts: [
        {
          id: "agent-loop",
          label: "智能体执行循环",
          description: "围绕目标、观察、计划、行动和反馈不断修正执行过程。",
          difficulty: "core",
          sourceAnchorIds
        },
        {
          id: "tool-use",
          label: "工具调用边界",
          description: "让模型通过外部工具读写文件、查询信息或执行动作，但仍需要验证结果。",
          difficulty: "core",
          sourceAnchorIds
        },
        {
          id: "multi-agent-review",
          label: "多智能体协作与审核",
          description: "按角色分派任务，并用审核点控制质量、合并和风险。",
          difficulty: "core",
          sourceAnchorIds
        }
      ],
      dependencies: [
        { from: "agent-loop", to: "tool-use", relation: "uses", sourceAnchorIds },
        { from: "tool-use", to: "multi-agent-review", relation: "requires_review", sourceAnchorIds }
      ],
      misconceptions: [
        {
          id: "more-agents-always-better",
          statement: "智能体数量越多，系统一定越可靠",
          correction: "更多智能体会增加协调成本，必须通过任务边界、共享产物和审核点控制质量。",
          conceptIds: ["multi-agent-review"],
          sourceAnchorIds,
          inferred: true
        }
      ],
      examples: [
        {
          id: "reviewed-tool-call",
          title: "带审核的工具调用",
          description: "智能体执行文件修改后，由审核角色检查证据和风险再进入下一步。",
          conceptIds: ["tool-use", "multi-agent-review"],
          sourceAnchorIds,
          kind: "transfer_example"
        }
      ]
    };
  }

  const conceptIds = ["hash-function", "collision", "load-factor"];
  return {
    conceptIds,
    concepts: [
      {
        id: "hash-function",
        label: "哈希函数",
        description: "把 key 映射到桶下标的规则。",
        difficulty: "core",
        sourceAnchorIds
      },
      {
        id: "collision",
        label: "哈希冲突",
        description: "不同 key 进入同一桶时需要额外处理。",
        difficulty: "core",
        sourceAnchorIds
      },
      {
        id: "load-factor",
        label: "负载因子",
        description: "元素数量与桶数量的比例，会影响冲突概率。",
        difficulty: "core",
        sourceAnchorIds
      }
    ],
    dependencies: [
      { from: "hash-function", to: "collision", relation: "enables", sourceAnchorIds },
      { from: "collision", to: "load-factor", relation: "applies_to", sourceAnchorIds }
    ],
    misconceptions: [
      {
        id: "always-o1",
        statement: "哈希表查找永远是 O(1)",
        correction: "平均接近 O(1)，但冲突严重时会变慢。",
        conceptIds: ["collision", "load-factor"],
        sourceAnchorIds,
        inferred: true
      }
    ],
    examples: [
      {
        id: "cache-key",
        title: "缓存 key 设计",
        description: "用 key 的区分度减少热点冲突。",
        conceptIds: ["hash-function", "collision"],
        sourceAnchorIds,
        kind: "transfer_example"
      }
    ]
  };
}

function buildMockLessonProfile(config: RunConfig): MockLessonProfile {
  if (isAgenticTopic(config.topic)) {
    return {
      defaultLessonId: "agentic-design-patterns-lesson",
      defaultTitle: "Agentic Design Patterns：可控协作式智能体系统",
      concepts: ["智能体执行循环", "工具调用边界", "多智能体协作", "人工审核", "记忆与评估"],
      dependencies: ["理解大模型基本输入输出", "知道工具调用会产生外部副作用"],
      examples: ["让一个智能体读取资料、调用工具、观察结果并修正计划", "把资料拆解、课程设计和审核交给不同角色协作"],
      misconceptionStatements: ["多智能体越多越好", "工具调用等于可靠执行", "一次生成可以替代过程验证"],
      candidateInteractions: ["选择任务分派方式并观察协作成本", "判断某个步骤是否需要人工审核"],
      prerequisites: ["理解大模型可以根据上下文生成文本", "知道工具调用会读写外部环境"],
      learningObjectives: [
        "解释智能体为什么需要观察、计划、行动和反馈循环",
        "区分模型推理、工具执行和结果验证的边界",
        "判断任务适合单智能体还是多智能体协作",
        "说明人工审核和评估如何降低自动化风险"
      ],
      pageSequence: [
        "问题场景：一次生成为什么不可控",
        "直觉：从独角戏到可审核流水线",
        "结构：任务、工具、记忆和审核点",
        "过程：观察-计划-行动-反馈循环",
        "互动：选择任务分派方式",
        "互动：判断是否需要人工审核",
        "检查：工具调用为什么不等于可靠执行",
        "误区：智能体越多越好吗",
        "走读：一个可控任务协议",
        "迁移：把论文处理拆成协作流程",
        "总结卡片"
      ],
      misconceptions: [
        {
          id: "misconception-more-agents",
          statement: "智能体数量越多，系统一定越可靠",
          correction: "更多智能体会增加协调成本，只有任务边界清晰、产物可检查时才有价值。"
        },
        {
          id: "misconception-tool-call",
          statement: "能调用工具就等于执行可靠",
          correction: "工具只负责动作，可靠性还依赖输入约束、结果观察、错误处理和审核。"
        },
        {
          id: "misconception-one-shot",
          statement: "一次完整生成可以替代过程验证",
          correction: "真实任务需要在关键产物后设置检查点，避免错误在后续步骤放大。"
        }
      ],
      transferTasks: [
        {
          id: "transfer-paper-workflow",
          prompt: "把一本技术书拆成总览、topic 拆课和审核流程",
          targetMentalModel: "用任务边界、共享产物和审核点设计可控协作。"
        },
        {
          id: "transfer-patent-review",
          prompt: "把专利解读任务拆成来源提取、概念映射、误区检查和教师版材料",
          targetMentalModel: "让不同角色围绕可验证中间产物协作，而不是堆叠一次性生成。"
        }
      ],
      summary: ["智能体系统的核心是可观察、可修正的执行循环", "工具调用必须配合验证和审核", "多智能体协作要先定义任务边界和交付物"],
      pageKind: "agentic"
    };
  }

  return {
    defaultLessonId: "database-index-lesson",
    defaultTitle: "为什么数据库索引能让查询更快",
    concepts: ["全表扫描", "索引查找", "选择性", "B+树直觉", "复合索引顺序", "写入与存储成本"],
    dependencies: ["基础 SQL 查询", "表、行、列的概念"],
    examples: ["在 1000 万行订单表中查找某个用户的订单", "比较无索引扫描和按 user_id 索引查找"],
    misconceptionStatements: ["索引总是让所有查询更快", "建越多索引越好", "复合索引中的列顺序不重要"],
    candidateInteractions: ["选择查询条件并观察扫描路径", "判断是否值得为某个场景添加索引"],
    prerequisites: ["会读简单 SELECT 查询", "理解表、行、列的基本关系"],
    learningObjectives: [
      "解释索引如何减少查询需要检查的数据范围",
      "区分全表扫描和索引查找的执行路径",
      "判断查询条件是否具有足够选择性",
      "说明索引带来的写入和存储成本"
    ],
    pageSequence: [
    "问题场景：1000 万行查询",
    "直觉：有目录和没有目录的书",
    "结构：表行与索引结构",
    "过程：全表扫描",
    "过程：索引查找",
    "互动：选择条件观察路径",
    "误区：索引总是有帮助",
    "SQL 走读：创建和使用索引",
    "迁移挑战：是否应该加索引",
    "总结卡片"
    ],
    misconceptions: [
      {
        id: "misconception-index-always-fast",
        statement: "索引并不总是让查询更快",
        correction: "索引只在能显著缩小候选数据范围时更有价值；低选择性查询可能仍然接近全表扫描。"
      },
      {
        id: "misconception-composite-order",
        statement: "复合索引中的列顺序不会影响查询",
        correction: "复合索引通常优先利用最左侧列，查询条件顺序和选择性会影响可用路径。"
      },
      {
        id: "misconception-more-indexes",
        statement: "索引越多数据库越快",
        correction: "每个索引都需要额外存储，并在写入、更新、删除时付出维护成本。"
      }
    ],
    transferTasks: [
      {
        id: "transfer-user-order-index",
        prompt: "判断用户订单查询是否适合为 user_id 建索引",
        targetMentalModel: "用读取频率、选择性、写入成本三项共同判断索引是否值得。"
      },
      {
        id: "transfer-log-search",
        prompt: "把选择性直觉迁移到日志检索和缓存键设计",
        targetMentalModel: "任何加速结构都在用额外组织方式换取更小的搜索空间。"
      }
    ],
    summary: ["索引通过缩小搜索空间提升读取效率", "高选择性条件更容易从索引获益", "索引会增加写入维护和存储成本"],
    pageKind: "database-index"
  };
}

function isAgenticTopic(topic: string): boolean {
  return /agent|智能体|多代理|多智能体/i.test(topic);
}

function buildLessonPages(targetPageCount: number, profile: MockLessonProfile): Array<{
  id: string;
  type: string;
  title: string;
  learningGoal: string;
  narrative: string;
  visualSpec?: Record<string, unknown>;
  interactionSpec?: Record<string, unknown>;
  assessmentSpec?: Record<string, unknown>;
  feedbackSpec?: Record<string, unknown>;
}> {
  const basePages = profile.pageKind === "agentic" ? buildAgenticBasePages() : buildDatabaseIndexBasePages();
  const selectedPages = selectPagesForTarget(basePages, targetPageCount);

  return Array.from({ length: targetPageCount }, (_, index) => {
    const page = selectedPages[index % selectedPages.length];
    return {
      id: `page-${String(index + 1).padStart(2, "0")}`,
      ...page
    };
  });
}

function selectPagesForTarget(basePages: MockBasePage[], targetPageCount: number): MockBasePage[] {
  const summaryPage = basePages.find((page) => page.type === "summary_card") ?? basePages.at(-1);
  if (!summaryPage || targetPageCount < 1) {
    return basePages;
  }

  if (targetPageCount < 8) {
    return [...basePages.slice(0, Math.max(targetPageCount - 1, 0)), summaryPage];
  }

  const requiredTypes = ["problem_scene", "intuition_visual", "structure_diagram", "interactive_model", "quiz", "misconception_check"];
  const requiredPages = requiredTypes.flatMap((type) => {
    if (type === "interactive_model") {
      return basePages.filter((page) => page.type === type).slice(0, 2);
    }
    const page = basePages.find((candidate) => candidate.type === type);
    return page ? [page] : [];
  });
  const optionalPages = basePages.filter((page) => !requiredPages.includes(page) && page !== summaryPage);
  const bodyTarget = targetPageCount - 1;
  const bodyPages = [...requiredPages];

  for (const optionalPage of optionalPages) {
    if (bodyPages.length >= bodyTarget) {
      break;
    }
    bodyPages.push(optionalPage);
  }

  while (bodyPages.length < bodyTarget) {
    bodyPages.push(basePages[bodyPages.length % basePages.length] ?? summaryPage);
  }

  return [...bodyPages.slice(0, bodyTarget), summaryPage];
}

function buildDatabaseIndexBasePages(): MockBasePage[] {
  return [
    {
      type: "problem_scene",
      title: "1000 万行里找一条记录",
      learningGoal: "感受无索引查询的搜索压力",
      narrative: "先从慢查询问题出发，而不是直接定义索引。",
      visualSpec: diagram("把 1000 万行看成一条很长的记录队列。", ["订单表", "候选行", "目标记录"])
    },
    {
      type: "intuition_visual",
      title: "有目录和没有目录的书",
      learningGoal: "建立索引缩小查找范围的直觉",
      narrative: "目录让读者跳到相关页，索引让数据库跳到相关范围。",
      visualSpec: diagram("对比顺序翻书和根据目录跳转。", ["没有目录", "目录项", "目标页"])
    },
    {
      type: "structure_diagram",
      title: "表行与索引结构",
      learningGoal: "看见数据表和索引之间的不同组织方式",
      narrative: "表按存储顺序排列，索引按键值组织并指向行。",
      visualSpec: diagram("展示数据行和索引键之间的指针关系。", ["表行", "索引键", "行指针"])
    },
    {
      type: "process_animation",
      title: "全表扫描如何工作",
      learningGoal: "理解逐行检查为什么随数据量增长变慢",
      narrative: "数据库需要把不匹配的行也检查一遍。",
      visualSpec: { ...diagram("逐行扫描的执行路径。", ["扫描指针", "已检查行", "未命中行"]), kind: "animation" }
    },
    {
      type: "interactive_model",
      title: "选择查询条件并观察路径",
      learningGoal: "判断查询是否能利用索引",
      narrative: "学习者改变条件，系统反馈全表扫描或索引查找。",
      interactionSpec: choiceInteraction("选择一个 WHERE 条件", "看到访问路径从全表扫描切换到索引查找。")
    },
    {
      type: "interactive_model",
      title: "判断是否值得添加索引",
      learningGoal: "把读取收益和写入成本放在一起判断",
      narrative: "学习者选择建或不建索引，系统解释读写取舍。",
      interactionSpec: choiceInteraction("选择是否添加索引", "看到读取收益、写入成本和存储成本的变化。")
    },
    {
      type: "quiz",
      title: "预测访问路径",
      learningGoal: "检查是否能根据查询条件预测执行路径",
      narrative: "先预测，再根据反馈修正心智模型。",
      assessmentSpec: multipleChoice("WHERE user_id = ? 且 user_id 有高选择性索引时，最可能的路径是什么？"),
      feedbackSpec: feedback("正确，因为索引能快速缩小候选范围。", "不对，请关注查询条件是否匹配高选择性索引。")
    },
    {
      type: "misconception_check",
      title: "索引总是有帮助吗",
      learningGoal: "识别低选择性和写入成本带来的反例",
      narrative: "索引不是免费加速器，它需要维护和空间。",
      assessmentSpec: multipleChoice("给低选择性的 status 字段单独建索引，一定会更快吗？"),
      feedbackSpec: feedback("正确，低选择性可能无法明显缩小范围。", "不一定，索引也有维护成本和选择性限制。")
    },
    {
      type: "code_walkthrough",
      title: "从 SQL 看到索引选择",
      learningGoal: "把直觉连接到 CREATE INDEX 和查询条件",
      narrative: "短 SQL 示例展示单列索引和复合索引顺序。"
    },
    {
      type: "transfer_challenge",
      title: "迁移到订单查询设计",
      learningGoal: "在新场景中决定是否加索引",
      narrative: "根据读取频率、选择性、写入成本做取舍。"
    },
    {
      type: "summary_card",
      title: "可迁移心智模型",
      learningGoal: "压缩索引决策规则",
      narrative: "索引用额外结构换取更小的搜索空间，但要支付维护成本。"
    }
  ];
}

function buildAgenticBasePages(): MockBasePage[] {
  return [
    {
      type: "problem_scene",
      title: "一次生成为什么不可控",
      learningGoal: "感受复杂任务需要过程控制",
      narrative: "先看一个真实问题：让模型一次性读资料、设计课程、写代码和自检，错误很容易在后续步骤放大。",
      visualSpec: diagram("把复杂任务拆成可观察的中间产物。", ["用户目标", "中间产物", "审核点"])
    },
    {
      type: "intuition_visual",
      title: "从独角戏到可审核流水线",
      learningGoal: "建立角色分工和检查点的直觉",
      narrative: "可控系统不是让一个模型一次说完，而是让任务沿着可检查的流水线推进。",
      visualSpec: diagram("对比一次性输出和分阶段交付。", ["一次性生成", "角色分工", "产物审核"])
    },
    {
      type: "structure_diagram",
      title: "任务、工具、记忆和审核点",
      learningGoal: "看见智能体系统的关键部件",
      narrative: "智能体围绕任务目标调用工具，读写状态，并在关键节点接受审核。",
      visualSpec: diagram("展示任务、工具、记忆、评估和人工审核之间的关系。", ["任务目标", "工具", "记忆", "审核"])
    },
    {
      type: "process_animation",
      title: "观察-计划-行动-反馈循环",
      learningGoal: "理解智能体为什么要根据结果修正计划",
      narrative: "每次行动之后都要观察结果，再决定继续、修正还是请求人工判断。",
      visualSpec: { ...diagram("展示智能体执行循环的状态变化。", ["观察", "计划", "行动", "反馈"]), kind: "animation" }
    },
    {
      type: "interactive_model",
      title: "选择任务分派方式",
      learningGoal: "判断什么时候需要多角色协作",
      narrative: "学习者选择单智能体或分角色执行，系统解释速度、质量和协调成本。",
      interactionSpec: agenticChoiceInteraction("选择任务分派方式", "看到单智能体和多智能体在成本、检查点和质量风险上的差异。")
    },
    {
      type: "interactive_model",
      title: "判断是否需要人工审核",
      learningGoal: "把风险和可逆性纳入流程设计",
      narrative: "学习者决定是否在关键产物后加入审核，系统解释为什么某些动作不能直接自动放行。",
      interactionSpec: agenticReviewInteraction()
    },
    {
      type: "quiz",
      title: "工具调用为什么不等于可靠执行",
      learningGoal: "检查是否能区分动作完成和结果正确",
      narrative: "能调用工具只说明动作发生了，不说明目标已经正确达成。",
      assessmentSpec: multipleChoice("智能体成功调用写文件工具后，下一步最应该做什么？", ["直接结束", "观察结果并验证是否符合目标", "再随机调用一个工具"], "观察结果并验证是否符合目标"),
      feedbackSpec: feedback("正确，可靠执行依赖观察、验证和必要的修正。", "不对，工具调用只是动作，结果仍然需要验证。")
    },
    {
      type: "misconception_check",
      title: "智能体越多越好吗",
      learningGoal: "识别多智能体协作的协调成本",
      narrative: "多角色可以提高覆盖面，但如果边界不清，会制造重复、冲突和审核负担。",
      assessmentSpec: multipleChoice("什么时候更适合引入多智能体？", ["任务可以拆成清晰角色且产物可审核", "任何任务都越多越好", "只要模型足够大就不需要边界"], "任务可以拆成清晰角色且产物可审核"),
      feedbackSpec: feedback("正确，多智能体价值来自清晰分工和可审核产物。", "不对，多智能体会带来协调成本，需要明确边界。")
    },
    {
      type: "code_walkthrough",
      title: "一个可控任务协议",
      learningGoal: "把直觉连接到可执行流程",
      narrative: "用短协议描述任务输入、中间产物、审核点和退出条件。"
    },
    {
      type: "transfer_challenge",
      title: "迁移到资料生成课程",
      learningGoal: "把协作式智能体系统迁移到学习材料生成",
      narrative: "为一本书设计来源提取、概念映射、拆课、生成和审核的任务分派。"
    },
    {
      type: "summary_card",
      title: "可控智能体系统心智模型",
      learningGoal: "压缩智能体流程设计规则",
      narrative: "智能体系统用过程、工具和审核把开放式生成变成可观察、可修正的工作流。"
    }
  ];
}

function diagram(description: string, keyElements: string[]): Record<string, unknown> {
  return {
    kind: "diagram",
    description,
    keyElements
  };
}

function choiceInteraction(learnerAction: string, expectedObservation: string): Record<string, unknown> {
  return {
    kind: "choice",
    learnerAction,
    expectedObservation,
    cognitivePurpose: "通过行动观察访问路径变化，建立因果心智模型。",
    options: [
      {
        id: "indexed",
        label: "选择高选择性索引条件",
        resultTitle: "索引查找",
        outcomeId: "indexed-path",
        resultTone: "success",
        explanation: "因为索引键能把候选范围缩小到少量记录。"
      },
      {
        id: "scan",
        label: "选择低选择性条件",
        resultTitle: "接近全表扫描",
        outcomeId: "scan-path",
        resultTone: "warning",
        explanation: "因为大量记录都满足条件，索引不能显著减少需要检查的数据。"
      }
    ]
  };
}

function agenticChoiceInteraction(learnerAction: string, expectedObservation: string): Record<string, unknown> {
  return {
    kind: "choice",
    learnerAction,
    expectedObservation,
    cognitivePurpose: "通过比较分派策略，理解多智能体协作的收益和协调成本。",
    options: [
      {
        id: "single-agent",
        label: "单智能体连续执行",
        resultTitle: "速度快但检查点少",
        outcomeId: "single-agent-path",
        resultTone: "warning",
        explanation: "适合低风险短任务；复杂资料处理容易缺少中间验证。"
      },
      {
        id: "role-split",
        label: "按角色拆分并审核",
        resultTitle: "更可控但协调成本更高",
        outcomeId: "role-split-path",
        resultTone: "success",
        explanation: "适合多文件、多阶段任务，因为每个中间产物都能被检查和修订。"
      }
    ]
  };
}

function agenticReviewInteraction(): Record<string, unknown> {
  return {
    kind: "choice",
    learnerAction: "选择是否加入人工审核",
    expectedObservation: "看到高风险步骤在审核后再进入下一阶段。",
    cognitivePurpose: "把风险、可逆性和证据质量纳入自动化流程设计。",
    options: [
      {
        id: "skip-review",
        label: "跳过审核继续执行",
        resultTitle: "速度提升但错误会传递",
        outcomeId: "skip-review",
        resultTone: "warning",
        explanation: "如果中间产物错误，后续课程、代码和测试都会建立在错误假设上。"
      },
      {
        id: "review-gate",
        label: "加入审核门槛",
        resultTitle: "节奏变慢但风险下降",
        outcomeId: "review-gate",
        resultTone: "success",
        explanation: "审核点让系统在关键决策前确认来源、边界和质量。"
      }
    ]
  };
}

function multipleChoice(prompt: string, options = ["索引查找", "全表扫描", "随机选择"], correctAnswer = "索引查找"): Record<string, unknown> {
  return {
    kind: "multiple_choice",
    prompt,
    options,
    correctAnswer
  };
}

function feedback(correctFeedback: string, incorrectFeedback: string): Record<string, unknown> {
  return {
    correctFeedback,
    incorrectFeedback
  };
}
